# Generated by Django 3.1.3 on 2020-12-16 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='persondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('phone', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('linkedin', models.CharField(max_length=127)),
                ('github', models.CharField(max_length=127)),
                ('dob', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=127)),
                ('father', models.CharField(max_length=127)),
                ('summary', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
