# Generated by Django 3.1.3 on 2020-12-18 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='address',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='dob',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='father',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='github',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='linkedin',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='summary',
            field=models.TextField(blank=True, max_length=2047),
        ),
        migrations.CreateModel(
            name='technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=127)),
                ('tools', models.CharField(max_length=127)),
                ('familiar', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, max_length=2047)),
                ('tech', models.CharField(blank=True, max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='internships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=127)),
                ('start', models.CharField(blank=True, max_length=127)),
                ('to', models.CharField(blank=True, max_length=127)),
                ('description', models.TextField(blank=True, max_length=2047)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('start', models.CharField(max_length=127)),
                ('end', models.CharField(max_length=127)),
                ('score', models.CharField(max_length=127)),
                ('subject', models.CharField(max_length=127)),
                ('location', models.CharField(blank=True, max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('source', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
